apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-service
  ports:
    - port: 5006
      targetPort: 5005
      nodePort: 30007

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  selector:
    matchLabels:
      app: my-service
  replicas: 1
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: elad2050/docker-demo:my-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5006